[package]
name = "rustyblog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.9.2"
web-sys = "0.3.61"
yew = { version = "0.20", features = ["csr"] }
